#!/bin/sh
#
# Splits text file with multiple Dynamics NAV object into many files, one per object.
# If no input file name is given, default name (all.txt) will be used instead.
#

if [ -n "$1" ] 
then
    ALL="$1"
else
    ALL="all.txt"
fi

awk '{
    sub(/$/,"\r"); 
    if (/(OBJECT ).*/) {
        sub(/^[ \t]+/, "");
        file = toupper(substr($2,1,3))$3".TXT";
        print > file;
    } else {
        print >> file; 
    }
}' "$ALL"
