#!/usr/bin/ruby -w
# vim:syntax=ruby

ARGV.each do|a|
  puts "Argument: #{a}"
end

if File.exist?("all.txt") then  
    f = File
    File.open("all.txt").each_line do |line|
        file_name = case 
            when line.match('^OBJECT Table.*')
                "TAB" + line.split[2] + ".TXT"
            when line.match('^OBJECT Form.*')
                "FOR" + line.split[2] + ".TXT"
            when line.match('^OBJECT Report.*')
                "REP" + line.split[2] + ".TXT"
            when line.match('^OBJECT Dataport.*')
                "DAT" + line.split[2] + ".TXT"
            when line.match('^OBJECT XMLPort.*')
                "XML" + line.split[2] + ".TXT"
            when line.match('^OBJECT Codeunit.*')
                "COD" + line.split[2] + ".TXT"
            when line.match("^OBJECT MenuSuite.*")
                "MEN" + line.split[2] + ".TXT"
            when line.match('^OBJECT Page.*')
                "PAG" + line.split[2] + ".TXT"
            when line.match('^OBJECT Query.*')
                "QUE" + line.split[2] + ".TXT"
        end
        
        unless file_name.nil? 
            puts file_name 
            File.exist?(file_name) { File.delete(file_name) }
            
            f = File.open(file_name,"w")
        end

        f.write(line)
    end 
end
